### ISSUE TITLE
uintX_t error

### ISSUE THREAD

**Issue by Florin9doi** [devos50/generate-ipod-touch-1g-nand#2]
https://github.com/devos50/generate-ipod-touch-1g-nand/blob/fdc4f465dffc944cf050514d7dbf2d57b5472150/ftl.h#L4

```diff
diff --git a/ftl.h b/ftl.h
index fb7f725..4b495fd 100644
--- a/ftl.h
+++ b/ftl.h
@@ -2,6 +2,7 @@
 #define FTL_H

 #include "wmr.h"
+#include <stdint.h>

 #define FTL_CXT_SECTION_SIZE 3
 #define FTL_SPARE_TYPE_CXT_INDEX 0x43
```

**Comment by devos50** [comment]
Thank you for creating an issue! If this fixes a compilation issue, could you please create a PR for it?
